### ISSUE TITLE
Remove float:left to not override pull-right

### ISSUE THREAD

**Issue by agold2** [SU-SWS/open_framework#117]
I was using the latest stable release and replaced it with HEAD to fix another issue, which introduced this new issue, where Bootstrap's pull-right class is being overridden by line 808 of open_framework.css

``` css
.region-navigation .block{
  float:left;
}
```

Is this CSS necessary, or can it be removed?

**Comment by hyperboy** [comment]
The CSS was designed to accommodate multiple menu blocks in the navigation region.  This looks like a CSS specificity issue.  We'll consider adding something like the following:

``` css
.region-navigation .block.pullright {
  float:right;
}
```
