### ISSUE TITLE
customizing shape of nav menu

### ISSUE THREAD

**Issue by BlueScot** [SU-SWS/open_framework#252]
I'm having a hard time trying to customize the shape of the navbar. Basically, I want a tapered corner to one side of the navbar. Similar to #test2 in this example. http://plnkr.co/edit/DmbiizPfycqTOG9Wqp0B?p=preview

I've attempted to work within a subtheme, but the navbar-inner and navbar div tags don't seem to achieve the affect i want. In fact, I've noticed that some properties seem to be entirely pointless. Such as attempting to change background-color using .navbar-inner {} in a subtheme configuration. 

Any help would be greatly appreciated.

**Comment by hyperboy** [comment]
Hi BlueScot,

In your subtheme, override the background image and webkit styles for the .navbar-inner div first, then apply the tapered corner styles.

Here's the Open Framework CSS.

``` css
.navbar-inner {
min-height: 40px;
padding-right: 20px;
padding-left: 20px;
background-color: #fafafa;
background-image: -moz-linear-gradient(top,#fff,#f2f2f2);
background-image: -webkit-gradient(linear,0 0,0 100%,from(#fff),to(#f2f2f2));
background-image: -webkit-linear-gradient(top,#fff,#f2f2f2);
background-image: -o-linear-gradient(top,#fff,#f2f2f2);
background-image: linear-gradient(to bottom,#fff,#f2f2f2);
background-repeat: repeat-x;
border: 1px solid #d4d4d4;
-webkit-border-radius: 4px;
-moz-border-radius: 4px;
border-radius: 4px;
filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff',endColorstr='#fff2f2f2',GradientType=0);
-moz-box-shadow: 0 1px 4px rgba(0,0,0,0.065);
box-shadow: 0 1px 4px rgba(0,0,0,0.065);
}
```

You can try the following reset CSS in your sub-theme.

``` css
.navbar-inner {
min-height: 0px;
padding-right: 0px;
padding-left: 0px;
background-color: transparent;
background-image: none;
background-repeat: repeat-x;
border: none;
-webkit-border-radius: 0px;
-moz-border-radius: 0px;
border-radius: 0px;
filter: none;
-moz-box-shadow: none;
box-shadow: none;
}
```
