### ISSUE TITLE
Footer content blocks have incorrect responsive widths

### ISSUE THREAD

**Issue by hyperboy** [SU-SWS/open_framework#312]
``` css
/* line 1265, ../sass/includes/_base.scss */
  .footer-content .block.span2,
  .footer-content .block.span3,
  .footer-content .block.span4 {
    float: left;
    margin-left: 0;
    margin-right: 4%;
    width: 30.6%;
  }
```

Consider removing right margin for last-child.
